plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}


group = 'expo.modules.kmpbridge'
version = '0.1.0'

repositories {
  mavenCentral()
  google()
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.aar'])
}

android {
  namespace "expo.modules.kmpbridge"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
