// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import ExpoModulesCore
import Shared

public class AsyncWorkerModule: Module {
  private let asyncWorker = AsyncWorker()

  public func definition() -> ModuleDefinition {
    Name("AsyncWorker")

    // Suspends briefly, then returns a fixed message. */
    AsyncFunction("fetchMessage") { (promise: Promise) in
      Task { [weak self] in
        guard let self else { return }
        do {
          let result = try await self.asyncWorker.fetchMessage()
          promise.resolve(result)
        } catch {
          promise.reject(error)
        }
      }
    }

    // Suspends, then returns the sum of two integers. */
    AsyncFunction("computeSum") { (a: Int32, b: Int32, promise: Promise) in
      Task { [weak self] in
        guard let self else { return }
        do {
          let result = try await self.asyncWorker.computeSum(a: a, b: b)
          promise.resolve(result)
        } catch {
          promise.reject(error)
        }
      }
    }

    // Waits for the given duration, then returns true. Exercises a Long parameter on a suspend function. */
    AsyncFunction("waitAndFlag") { (delayMs: Double, promise: Promise) in
      Task { [weak self] in
        guard let self else { return }
        do {
          let result = try await self.asyncWorker.waitAndFlag(delayMs: Int64(delayMs))
          promise.resolve(result)
        } catch {
          promise.reject(error)
        }
      }
    }
  }
}
