// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import ExpoModulesCore
import Shared

public class CalculatorModule: Module {
  private let calculator = Calculator()

  public func definition() -> ModuleDefinition {
    Name("Calculator")

    // Adds two 32-bit integers. */
    Function("addInts") { (a: Int32, b: Int32) in
      return self.calculator.addInts(a: a, b: b)
    }

    // Adds two doubles. */
    Function("addDoubles") { (a: Double, b: Double) in
      return self.calculator.addDoubles(a: a, b: b)
    }

    // Adds two 64-bit longs. JS sends these as Double; the bridge casts back to Long.
    Function("addLongs") { (a: Double, b: Double) in
      return self.calculator.addLongs(a: Int64(a), b: Int64(b))
    }

    // Multiplies two floats. */
    Function("multiplyFloats") { (a: Float, b: Float) in
      return self.calculator.multiplyFloats(a: a, b: b)
    }

    // Inverts a boolean.
    Function("negate") { (value: Bool) in
      return self.calculator.negate(value: value)
    }

    // Builds a human-readable description from a label and a count.
    // Declared across multiple lines on purpose to exercise the parser's
    // multi-line signature accumulation.
    Function("describe") { (label: String, count: Int32) in
      return self.calculator.describe(label: label, count: count)
    }

    // Returns nothing — exercises the Unit/void bridge path. */
    Function("reset") {
      return self.calculator.reset()
    }
  }
}
