// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import ExpoModulesCore
import Shared

public class GreetingModule: Module {
  private let greeting = Greeting()
  private enum FlowKey { case counter }
  private var flowTasks: [FlowKey: Task<Void, Never>] = [:]

  public func definition() -> ModuleDefinition {
    Name("Greeting")

    Events("onCounterUpdate")

    OnDestroy {
      self.flowTasks.values.forEach { $0.cancel() }
    }

    Function("greet") { (name: String) in
      return self.greeting.greet(name: name)
    }

    Function("greeting2") {
      return self.greeting.greeting2()
    }

    Function("greeting3") {
      return self.greeting.greeting3()
    }

    // hello this o=is greeting4
    Function("greeting4") {
      return self.greeting.greeting4()
    }

    Function("startCounter") {
      self.flowTasks[.counter]?.cancel()
      self.flowTasks[.counter] = Task { [weak self] in
        guard let self else { return }
        for await value in self.greeting.counterFlow() {
          self.sendEvent("onCounterUpdate", ["value": value.intValue])
        }
      }
    }

    Function("stopCounter") {
      self.flowTasks[.counter]?.cancel()
      self.flowTasks[.counter] = nil
    }

    AsyncFunction("delayedEcho") { (text: String, delayMs: Double, promise: Promise) in
      Task { [weak self] in
        guard let self else { return }
        do {
          let result = try await self.greeting.delayedEcho(text: text, delayMs: Int64(delayMs))
          promise.resolve(result)
        } catch {
          promise.reject(error)
        }
      }
    }
  }
}
