// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import ExpoModulesCore
import Shared

public class TickerServiceModule: Module {
  private let tickerService = TickerService()
  private enum FlowKey { case seconds, status, pulse }
  private var flowTasks: [FlowKey: Task<Void, Never>] = [:]

  public func definition() -> ModuleDefinition {
    Name("TickerService")

    Events("onSecondsUpdate", "onStatusUpdate", "onPulseUpdate")

    OnDestroy {
      self.flowTasks.values.forEach { $0.cancel() }
    }

    // Emits an incrementing second counter once per second. */
    Function("startSeconds") {
      self.flowTasks[.seconds]?.cancel()
      self.flowTasks[.seconds] = Task { [weak self] in
        guard let self else { return }
        for await value in self.tickerService.secondsFlow() {
          self.sendEvent("onSecondsUpdate", ["value": value.intValue])
        }
      }
    }

    Function("stopSeconds") {
      self.flowTasks[.seconds]?.cancel()
      self.flowTasks[.seconds] = nil
    }

    // Emits a rotating status label every two seconds. */
    Function("startStatus") {
      self.flowTasks[.status]?.cancel()
      self.flowTasks[.status] = Task { [weak self] in
        guard let self else { return }
        for await value in self.tickerService.statusFlow() {
          self.sendEvent("onStatusUpdate", ["value": value])
        }
      }
    }

    Function("stopStatus") {
      self.flowTasks[.status]?.cancel()
      self.flowTasks[.status] = nil
    }

    // Emits an alternating boolean pulse every 500ms. */
    Function("startPulse") {
      self.flowTasks[.pulse]?.cancel()
      self.flowTasks[.pulse] = Task { [weak self] in
        guard let self else { return }
        for await value in self.tickerService.pulseFlow() {
          self.sendEvent("onPulseUpdate", ["value": value.boolValue])
        }
      }
    }

    Function("stopPulse") {
      self.flowTasks[.pulse]?.cancel()
      self.flowTasks[.pulse] = nil
    }
  }
}
