// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import ExpoModulesCore
import Shared

public class TrafficLightModule: Module {
  private let trafficLight = TrafficLight()
  private enum FlowKey { case color }
  private var flowTasks: [FlowKey: Task<Void, Never>] = [:]

  public func definition() -> ModuleDefinition {
    Name("TrafficLight")

    Events("onColorUpdate")

    OnDestroy {
      self.flowTasks.values.forEach { $0.cancel() }
    }

    // Returns the current light color (enum return value). */
    Function("currentColor") {
      return self.trafficLight.currentColor().name
    }

    // Returns true when the given color means "stop" (enum parameter). */
    Function("isStop") { (color: String) in
      return self.trafficLight.isStop(color: decodeLightColor(color))
    }

    // Emits the light color as it cycles RED → YELLOW → GREEN (enum Flow element). */
    Function("startColor") {
      self.flowTasks[.color]?.cancel()
      self.flowTasks[.color] = Task { [weak self] in
        guard let self else { return }
        for await value in self.trafficLight.colorFlow() {
          self.sendEvent("onColorUpdate", ["value": value.name])
        }
      }
    }

    Function("stopColor") {
      self.flowTasks[.color]?.cancel()
      self.flowTasks[.color] = nil
    }
  }
}

fileprivate func decodeLightColor(_ raw: String) -> LightColor {
  return LightColor.allCases.first(where: { $0.name == raw }) ?? LightColor.allCases[0]
}
