/**
 * Expo config plugin: include the KMP `shared` module as a Gradle project
 * dependency so the Android build always compiles it directly instead of
 * resolving a stale AAR from mavenLocal.
 *
 * Appends to `android/settings.gradle` (regenerated by `expo prebuild`):
 *   include ':shared'
 *   project(':shared').projectDir = new File('../shared')
 */
const { withSettingsGradle } = require("@expo/config-plugins");

function addSharedProject(contents) {
  if (contents.includes("include ':shared'")) {
    return contents;
  }
  return (
    contents.trimEnd() +
    "\n\ninclude ':shared'\nproject(':shared').projectDir = new File('../shared')\n"
  );
}

module.exports = function withKmpSharedProject(config) {
  return withSettingsGradle(config, (config) => {
    config.modResults.contents = addSharedProject(config.modResults.contents);
    return config;
  });
};
