/**
 * Expo config plugin: add `mavenLocal()` to the Android root project's
 * repositories so the app can resolve the KMP `shared` module that we publish
 * via `./scripts/sync-kmp.sh` (i.e. `cd shared && ./gradlew publishToMavenLocal`).
 *
 * Needed because `android/build.gradle` is regenerated by `expo prebuild`, and
 * the `:app` configuration resolves the KMP dependency transitively using the
 * ROOT repositories (a repositories block inside the module isn't consulted for
 * the app's classpath resolution).
 */
const { withProjectBuildGradle } = require("@expo/config-plugins");

function addMavenLocal(contents) {
  if (contents.includes("mavenLocal()")) {
    return contents;
  }
  // Insert mavenLocal() as the first entry in `allprojects { repositories { ... } }`.
  const anchor = /allprojects\s*\{\s*repositories\s*\{/;
  if (!anchor.test(contents)) {
    throw new Error(
      "withKmpMavenLocal: could not find `allprojects { repositories {` in android/build.gradle"
    );
  }
  return contents.replace(anchor, (match) => `${match}\n    mavenLocal()`);
}

module.exports = function withKmpMavenLocal(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error(
        "withKmpMavenLocal: expected android/build.gradle to be Groovy"
      );
    }
    config.modResults.contents = addMavenLocal(config.modResults.contents);
    return config;
  });
};
