// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import { NativeModule, requireNativeModule } from 'expo';

type AsyncWorkerEvents = Record<string, never>;

declare class AsyncWorkerModule extends NativeModule<AsyncWorkerEvents> {
  // Suspends briefly, then returns a fixed message. */
  fetchMessage(): Promise<string>;
  // Suspends, then returns the sum of two integers. */
  computeSum(a: number, b: number): Promise<number>;
  // Waits for the given duration, then returns true. Exercises a Long parameter on a suspend function. */
  waitAndFlag(delayMs: number): Promise<boolean>;
}

export default requireNativeModule<AsyncWorkerModule>('AsyncWorker');
