// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import { NativeModule, requireNativeModule } from 'expo';

type CalculatorEvents = Record<string, never>;

declare class CalculatorModule extends NativeModule<CalculatorEvents> {
  // Adds two 32-bit integers. */
  addInts(a: number, b: number): number;
  // Adds two doubles. */
  addDoubles(a: number, b: number): number;
  // Adds two 64-bit longs. JS sends these as Double; the bridge casts back to Long.
  addLongs(a: number, b: number): number;
  // Multiplies two floats. */
  multiplyFloats(a: number, b: number): number;
  // Inverts a boolean.
  negate(value: boolean): boolean;
  // Builds a human-readable description from a label and a count.
  // Declared across multiple lines on purpose to exercise the parser's
  // multi-line signature accumulation.
  describe(label: string, count: number): string;
  // Returns nothing — exercises the Unit/void bridge path. */
  reset(): void;
}

export default requireNativeModule<CalculatorModule>('Calculator');
