// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import { NativeModule, requireNativeModule } from 'expo';

type GreetingEvents = {
  onCounterUpdate: (event: { value: number }) => void;
};

declare class GreetingModule extends NativeModule<GreetingEvents> {
  greet(name: string): string;
  greeting2(): string;
  greeting3(): string;
  // hello this o=is greeting4
  greeting4(): string;
  startCounter(): void;
  stopCounter(): void;
  delayedEcho(text: string, delayMs: number): Promise<string>;
}

export default requireNativeModule<GreetingModule>('Greeting');
