// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import { NativeModule, requireNativeModule } from 'expo';

type TickerServiceEvents = {
  onSecondsUpdate: (event: { value: number }) => void;
  onStatusUpdate: (event: { value: string }) => void;
  onPulseUpdate: (event: { value: boolean }) => void;
};

declare class TickerServiceModule extends NativeModule<TickerServiceEvents> {
  // Emits an incrementing second counter once per second. */
  startSeconds(): void;
  stopSeconds(): void;
  // Emits a rotating status label every two seconds. */
  startStatus(): void;
  stopStatus(): void;
  // Emits an alternating boolean pulse every 500ms. */
  startPulse(): void;
  stopPulse(): void;
}

export default requireNativeModule<TickerServiceModule>('TickerService');
