// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import { NativeModule, requireNativeModule } from 'expo';

type TrafficLightEvents = {
  onColorUpdate: (event: { value: unknown }) => void;
};

declare class TrafficLightModule extends NativeModule<TrafficLightEvents> {
  // Returns the current light color (enum return value). */
  currentColor(): unknown;
  // Returns true when the given color means "stop" (enum parameter). */
  isStop(color: unknown): boolean;
  // Emits the light color as it cycles RED → YELLOW → GREEN (enum Flow element). */
  startColor(): void;
  stopColor(): void;
}

export default requireNativeModule<TrafficLightModule>('TrafficLight');
