// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.
package expo.modules.kmpbridge

import com.example.shared.AsyncWorker
import expo.modules.kotlin.Promise
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

class AsyncWorkerModule : Module() {
  private val asyncWorker = AsyncWorker()
  private val scope = CoroutineScope(Dispatchers.Default + SupervisorJob())

  override fun definition() = ModuleDefinition {
    Name("AsyncWorker")

    OnDestroy {
      scope.cancel()
    }

    // Suspends briefly, then returns a fixed message. */
    AsyncFunction("fetchMessage") { promise: Promise ->
      scope.launch {
        try {
          promise.resolve(asyncWorker.fetchMessage())
        } catch (e: Exception) {
          promise.reject("FETCH_MESSAGE_ERROR", e.message, e)
        }
      }
    }

    // Suspends, then returns the sum of two integers. */
    AsyncFunction("computeSum") { a: Int, b: Int, promise: Promise ->
      scope.launch {
        try {
          promise.resolve(asyncWorker.computeSum(a, b))
        } catch (e: Exception) {
          promise.reject("COMPUTE_SUM_ERROR", e.message, e)
        }
      }
    }

    // Waits for the given duration, then returns true. Exercises a Long parameter on a suspend function. */
    AsyncFunction("waitAndFlag") { delayMs: Double, promise: Promise ->
      scope.launch {
        try {
          promise.resolve(asyncWorker.waitAndFlag(delayMs.toLong()))
        } catch (e: Exception) {
          promise.reject("WAIT_AND_FLAG_ERROR", e.message, e)
        }
      }
    }
  }
}
