// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.
package expo.modules.kmpbridge

import com.example.shared.Calculator
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition

class CalculatorModule : Module() {
  private val calculator = Calculator()

  override fun definition() = ModuleDefinition {
    Name("Calculator")

    // Adds two 32-bit integers. */
    Function("addInts") { a: Int, b: Int ->
      calculator.addInts(a, b)
    }

    // Adds two doubles. */
    Function("addDoubles") { a: Double, b: Double ->
      calculator.addDoubles(a, b)
    }

    // Adds two 64-bit longs. JS sends these as Double; the bridge casts back to Long.
    Function("addLongs") { a: Double, b: Double ->
      calculator.addLongs(a.toLong(), b.toLong())
    }

    // Multiplies two floats. */
    Function("multiplyFloats") { a: Float, b: Float ->
      calculator.multiplyFloats(a, b)
    }

    // Inverts a boolean.
    Function("negate") { value: Boolean ->
      calculator.negate(value)
    }

    // Builds a human-readable description from a label and a count.
    // Declared across multiple lines on purpose to exercise the parser's
    // multi-line signature accumulation.
    Function("describe") { label: String, count: Int ->
      calculator.describe(label, count)
    }

    // Returns nothing — exercises the Unit/void bridge path. */
    Function("reset") {
      calculator.reset()
    }
  }
}
