// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.
package expo.modules.kmpbridge

import com.example.shared.Greeting
import expo.modules.kotlin.Promise
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

class GreetingModule : Module() {
  private val greeting = Greeting()
  private val scope = CoroutineScope(Dispatchers.Default + SupervisorJob())
  private enum class FlowKey { COUNTER }
  private val flowJobs = mutableMapOf<FlowKey, Job>()

  override fun definition() = ModuleDefinition {
    Name("Greeting")

    Events("onCounterUpdate")

    OnDestroy {
      scope.cancel()
    }

    Function("greet") { name: String ->
      greeting.greet(name)
    }

    Function("greeting2") {
      greeting.greeting2()
    }

    Function("greeting3") {
      greeting.greeting3()
    }

    // hello this o=is greeting4
    Function("greeting4") {
      greeting.greeting4()
    }

    Function("startCounter") {
      flowJobs[FlowKey.COUNTER]?.cancel()
      flowJobs[FlowKey.COUNTER] = scope.launch {
        greeting.counterFlow().collect { value ->
          sendEvent("onCounterUpdate", mapOf("value" to value))
        }
      }
    }

    Function("stopCounter") {
      flowJobs[FlowKey.COUNTER]?.cancel()
      flowJobs.remove(FlowKey.COUNTER)
    }

    AsyncFunction("delayedEcho") { text: String, delayMs: Double, promise: Promise ->
      scope.launch {
        try {
          promise.resolve(greeting.delayedEcho(text, delayMs.toLong()))
        } catch (e: Exception) {
          promise.reject("DELAYED_ECHO_ERROR", e.message, e)
        }
      }
    }
  }
}
