// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.
package expo.modules.kmpbridge

import com.example.shared.TickerService
import expo.modules.kotlin.Promise
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

class TickerServiceModule : Module() {
  private val tickerService = TickerService()
  private val scope = CoroutineScope(Dispatchers.Default + SupervisorJob())
  private enum class FlowKey { SECONDS, STATUS, PULSE }
  private val flowJobs = mutableMapOf<FlowKey, Job>()

  override fun definition() = ModuleDefinition {
    Name("TickerService")

    Events("onSecondsUpdate", "onStatusUpdate", "onPulseUpdate")

    OnDestroy {
      scope.cancel()
    }

    // Emits an incrementing second counter once per second. */
    Function("startSeconds") {
      flowJobs[FlowKey.SECONDS]?.cancel()
      flowJobs[FlowKey.SECONDS] = scope.launch {
        tickerService.secondsFlow().collect { value ->
          sendEvent("onSecondsUpdate", mapOf("value" to value))
        }
      }
    }

    Function("stopSeconds") {
      flowJobs[FlowKey.SECONDS]?.cancel()
      flowJobs.remove(FlowKey.SECONDS)
    }

    // Emits a rotating status label every two seconds. */
    Function("startStatus") {
      flowJobs[FlowKey.STATUS]?.cancel()
      flowJobs[FlowKey.STATUS] = scope.launch {
        tickerService.statusFlow().collect { value ->
          sendEvent("onStatusUpdate", mapOf("value" to value))
        }
      }
    }

    Function("stopStatus") {
      flowJobs[FlowKey.STATUS]?.cancel()
      flowJobs.remove(FlowKey.STATUS)
    }

    // Emits an alternating boolean pulse every 500ms. */
    Function("startPulse") {
      flowJobs[FlowKey.PULSE]?.cancel()
      flowJobs[FlowKey.PULSE] = scope.launch {
        tickerService.pulseFlow().collect { value ->
          sendEvent("onPulseUpdate", mapOf("value" to value))
        }
      }
    }

    Function("stopPulse") {
      flowJobs[FlowKey.PULSE]?.cancel()
      flowJobs.remove(FlowKey.PULSE)
    }
  }
}
