// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.
package expo.modules.kmpbridge

import com.example.shared.TrafficLight
import com.example.shared.LightColor
import expo.modules.kotlin.Promise
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

class TrafficLightModule : Module() {
  private val trafficLight = TrafficLight()
  private val scope = CoroutineScope(Dispatchers.Default + SupervisorJob())
  private enum class FlowKey { COLOR }
  private val flowJobs = mutableMapOf<FlowKey, Job>()

  override fun definition() = ModuleDefinition {
    Name("TrafficLight")

    Events("onColorUpdate")

    OnDestroy {
      scope.cancel()
    }

    // Returns the current light color (enum return value). */
    Function("currentColor") {
      trafficLight.currentColor().name
    }

    // Returns true when the given color means "stop" (enum parameter). */
    Function("isStop") { color: String ->
      trafficLight.isStop(LightColor.valueOf(color))
    }

    // Emits the light color as it cycles RED → YELLOW → GREEN (enum Flow element). */
    Function("startColor") {
      flowJobs[FlowKey.COLOR]?.cancel()
      flowJobs[FlowKey.COLOR] = scope.launch {
        trafficLight.colorFlow().collect { value ->
          sendEvent("onColorUpdate", mapOf("value" to value.name))
        }
      }
    }

    Function("stopColor") {
      flowJobs[FlowKey.COLOR]?.cancel()
      flowJobs.remove(FlowKey.COLOR)
    }
  }
}
