// AUTO-GENERATED by shared-artifacts bridge generator. DO NOT EDIT.
// Re-run `bash scripts/push-bridges.sh` from shared-artifacts to regenerate.

import CalculatorNative from './src/CalculatorModule';
import TrafficLightNative from './src/TrafficLightModule';
import AsyncWorkerNative from './src/AsyncWorkerModule';
import TickerServiceNative from './src/TickerServiceModule';
import GreetingNative from './src/GreetingModule';

export enum LightColor {
  RED = 'RED',
  YELLOW = 'YELLOW',
  GREEN = 'GREEN',
}

export const Calculator = {
  // Adds two 32-bit integers. */
  addInts: (a: number, b: number): number => CalculatorNative.addInts(a, b),
  // Adds two doubles. */
  addDoubles: (a: number, b: number): number => CalculatorNative.addDoubles(a, b),
  // Adds two 64-bit longs. JS sends these as Double; the bridge casts back to Long.
  addLongs: (a: number, b: number): number => CalculatorNative.addLongs(a, b),
  // Multiplies two floats. */
  multiplyFloats: (a: number, b: number): number => CalculatorNative.multiplyFloats(a, b),
  // Inverts a boolean.
  negate: (value: boolean): boolean => CalculatorNative.negate(value),
  // Builds a human-readable description from a label and a count.
  // Declared across multiple lines on purpose to exercise the parser's
  // multi-line signature accumulation.
  describe: (label: string, count: number): string => CalculatorNative.describe(label, count),
  // Returns nothing — exercises the Unit/void bridge path. */
  reset: (): void => CalculatorNative.reset(),
};

export const TrafficLight = {
  // Returns the current light color (enum return value). */
  currentColor: (): LightColor => TrafficLightNative.currentColor() as LightColor,
  // Returns true when the given color means "stop" (enum parameter). */
  isStop: (color: LightColor): boolean => TrafficLightNative.isStop(color),
  // Emits the light color as it cycles RED → YELLOW → GREEN (enum Flow element). */
  startColor: (): void => TrafficLightNative.startColor(),
  stopColor: (): void => TrafficLightNative.stopColor(),
  addColorListener: (handler: (event: { value: LightColor }) => void) =>
    TrafficLightNative.addListener('onColorUpdate', (e) => handler({ value: e.value as LightColor })),
};

export const AsyncWorker = {
  // Suspends briefly, then returns a fixed message. */
  fetchMessage: (): Promise<string> => AsyncWorkerNative.fetchMessage(),
  // Suspends, then returns the sum of two integers. */
  computeSum: (a: number, b: number): Promise<number> => AsyncWorkerNative.computeSum(a, b),
  // Waits for the given duration, then returns true. Exercises a Long parameter on a suspend function. */
  waitAndFlag: (delayMs: number): Promise<boolean> => AsyncWorkerNative.waitAndFlag(delayMs),
};

export const TickerService = {
  // Emits an incrementing second counter once per second. */
  startSeconds: (): void => TickerServiceNative.startSeconds(),
  stopSeconds: (): void => TickerServiceNative.stopSeconds(),
  addSecondsListener: (handler: (event: { value: number }) => void) =>
    TickerServiceNative.addListener('onSecondsUpdate', handler),
  // Emits a rotating status label every two seconds. */
  startStatus: (): void => TickerServiceNative.startStatus(),
  stopStatus: (): void => TickerServiceNative.stopStatus(),
  addStatusListener: (handler: (event: { value: string }) => void) =>
    TickerServiceNative.addListener('onStatusUpdate', handler),
  // Emits an alternating boolean pulse every 500ms. */
  startPulse: (): void => TickerServiceNative.startPulse(),
  stopPulse: (): void => TickerServiceNative.stopPulse(),
  addPulseListener: (handler: (event: { value: boolean }) => void) =>
    TickerServiceNative.addListener('onPulseUpdate', handler),
};

export const Greeting = {
  greet: (name: string): string => GreetingNative.greet(name),
  greeting2: (): string => GreetingNative.greeting2(),
  greeting3: (): string => GreetingNative.greeting3(),
  // hello this o=is greeting4
  greeting4: (): string => GreetingNative.greeting4(),
  startCounter: (): void => GreetingNative.startCounter(),
  stopCounter: (): void => GreetingNative.stopCounter(),
  addCounterListener: (handler: (event: { value: number }) => void) =>
    GreetingNative.addListener('onCounterUpdate', handler),
  delayedEcho: (text: string, delayMs: number): Promise<string> => GreetingNative.delayedEcho(text, delayMs),
};

